# Generated by Django 4.1 on 2022-08-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='customer_id',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
